version: '3.3'
services:
  db:
    image: postgres:alpine
    container_name: helion_db
    restart: always
    environment:
      POSTGRES_USER: helion
      POSTGRES_PASSWORD: helion
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  adminer:
    image: dpage/pgadmin4:latest
    container_name: helion_db_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: helion@helion.pl
      PGADMIN_DEFAULT_PASSWORD: helion
    ports:
      - 8080:80
    depends_on:
      - db
